sudo: false
language: python
python:
#  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - pypy
  - pyp3
script: nosetests
install:
  - pip install -r requirements.txt
notifications:
  email: oczkers@gmail.com
